datapath: "./data"
savepath: "./output"
device: "cuda:0"
seed: 0
epochs: 50
batch_size: 64
learning_rate: 0.01
momentum: 0.5
val_freq: 10
ckpt_freq: 50
in_dim: 784
hidden_dims:
  - 100
out_dim: 10
mean: 0.1307
std: 0.3081